### ISSUE TITLE
fastd 22 build issue

### ISSUE THREAD

**Issue by chenrui333** [NeoRaider/fastd#19]
> clang -Isrc/liblibfastd.a.p -Isrc -I../src -I/opt/homebrew/Cellar/libuecc/7/include/libuecc-7 -I/opt/homebrew/Cellar/json-c/0.15/include -I/opt/homebrew/Cellar/json-c/0.15/include/json-c -I/opt/homebrew/Cellar/openssl@1.1/1.1.1k/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c99 -O3 -D_GNU_SOURCE -D__APPLE_USE_RFC_3542 -MD -MQ src/liblibfastd.a.p/handshake.c.o -MF src/liblibfastd.a.p/handshake.c.o.d -o src/liblibfastd.a.p/handshake.c.o -c ../src/handshake.c
../src/handshake.c:293:14: error: implicit declaration of function 'htobe16' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
.length = htobe16(sizeof(header)),
^
1 error generated.

relates to 
- Homebrew/homebrew-core#80211

full build log:
https://github.com/Homebrew/homebrew-core/runs/2939005147

**Comment by NeoRaider** [comment]
Sorry about that, I currently don't have a MacOS host for build tests. Please test the fix in #20.

**Comment by chenrui333** [comment]
no worries apply your patch commit in this PR 
- Homebrew/homebrew-core#80211

**Comment by chenrui333** [comment]
@NeoRaider the fix works for me (just tested out on my Mojave machine), thanks!
