### ISSUE TITLE
OpenBSD tap interface

### ISSUE THREAD

**Issue by pierlu** [NeoRaider/fastd#2]
Fastd, last version compiles fine on OpenBSD 6.6 (October 2019 release).

Configuring with tap interface 

```
mode tap;
interface "tap2" ;
```

complains with an error: 

`2019-10-25 18:18:08 +0200 --- Error: config error: tap2 doesn't seem to be a TUN device`

I think issue is related to the tun/tap equivalence on the past OpenBSD versions. 
Now tap(4) is a separate device.

**Comment by NeoRaider** [comment]
Hmm, interesting. It's been a while since I last had a look at OpenBSD, do you know when tap became a separate device?

I might have time to look into this soon-ish, but patches are also very welcome.

**Comment by dahlberg-fkie** [comment]
Happened "a long long time ago" in Oct 2015 (->59)
https://cvsweb.openbsd.org/src/sys/net/if_tun.c?rev=1.156&content-type=text/x-cvsweb-markup
