### ISSUE TITLE
Explain what fastd is

### ISSUE THREAD

**Issue by jacktose** [NeoRaider/fastd#22]
Neither the [readme], the [wiki], nor the [docs] answer the question, “What is fastd?” I've read most of them and I still don't know.
I suggest adding an introduction section or just the sentence, “fastd is ________.” at the top.

[readme]: https://github.com/NeoRaider/fastd/blob/main/README.md
[wiki]: https://github.com/NeoRaider/fastd/wiki
[docs]: https://fastd.readthedocs.io/en/stable/

**Comment by rubo77** [comment]
The man page states:

> fastd is a very small VPN daemon which tunnels IP packets and Ethernet frames over UDP. It supports various modern encryption and authentication schemes and can be used in many different network topologies (1:1, 1:n, meshed)
